name: "Build and Push Images to ECR"
description: "Image build and push to ECR"
runs:
  using: "composite"
  
  steps:
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: ${{ inputs.repository_name }}
      shell: bash
      run: |
        IMAGE_TAG=$(cat ./app_config.json | jq -r '.app_version')
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

